/*
 * Copyright 2009 Georgios "cyberpython" Migdos cyberpython@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License
 *       at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * CommandsListCellRenderer.java
 *
 * Created on 14 Ιανουάριος 2009, 8:38 μμ
 */

package glossaeditor.ui.components.commandslist;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author  cyberpython
 */
public class CommandsListCellRenderer extends javax.swing.JPanel implements ListCellRenderer {

    /** Creates new form CommandsListCellRenderer */
    public CommandsListCellRenderer() {
        initComponents();
    }
    
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        
        boolean selectable = false;
        
        if(value == null){       
            
        }        
        else if(value instanceof CommandsListItem){
            jLabel1.setVisible(true);
            jSeparator1.setVisible(false);
            this.jLabel1.setText(((CommandsListItem)value).getTitle());   
            selectable = true;
        }
        else if(value instanceof String){
            String s = (String) value;
            if(s.trim().toLowerCase().equals("separator")){
                jLabel1.setVisible(false);
                jSeparator1.setVisible(true);
            }
            else{
                jLabel1.setVisible(true);
                jSeparator1.setVisible(false);
                jLabel1.setText(" ");   
            }
        }        
        else{
            jLabel1.setVisible(true);
                jSeparator1.setVisible(false);
                jLabel1.setText(" ");
        }
        
        jLabel1.setFont(list.getFont());
        
        if (isSelected && selectable) {
                this.setBackground(list.getSelectionBackground());
                this.setForeground(list.getSelectionForeground());                
                jLabel1.setBackground(list.getSelectionBackground());
                jLabel1.setForeground(list.getSelectionForeground());
                
            } else {
                this.setBackground(list.getBackground());
                this.setForeground(list.getForeground());                
                jLabel1.setBackground(list.getBackground());
                jLabel1.setForeground(list.getForeground());
            }
            setEnabled(list.isEnabled());
        
        return this;
    }
    
    public void initialize(CommandsListItem item, int index){  
                    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(glossaeditor.Slang.class).getContext().getResourceMap(CommandsListCellRenderer.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
