/* This file was generated by SableCC (http://www.sablecc.org/). */

package glossaeditor.export.htmlgenerator.node;

import glossaeditor.export.htmlgenerator.analysis.*;

@SuppressWarnings("nls")
public final class TBrackets extends Token
{
    public TBrackets(String text)
    {
        setText(text);
    }

    public TBrackets(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBrackets(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBrackets(this);
    }
}
