/* This file was generated by SableCC (http://www.sablecc.org/). */

package glossaeditor.export.htmlgenerator.node;

import glossaeditor.export.htmlgenerator.analysis.*;

@SuppressWarnings("nls")
public final class TSpace extends Token
{
    public TSpace()
    {
        super.setText(" ");
    }

    public TSpace(int line, int pos)
    {
        super.setText(" ");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSpace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSpace(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSpace text.");
    }
}
