/* This file was generated by SableCC (http://www.sablecc.org/). */

package glossaeditor.export.htmlgenerator.analysis;

import glossaeditor.export.htmlgenerator.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTComment(TComment node);
    void caseTLineEnd(TLineEnd node);
    void caseTSpace(TSpace node);
    void caseTTab(TTab node);
    void caseTDataType(TDataType node);
    void caseTKeyword(TKeyword node);
    void caseTAssign(TAssign node);
    void caseTDifferent(TDifferent node);
    void caseTLt(TLt node);
    void caseTGt(TGt node);
    void caseTLte(TLte node);
    void caseTGte(TGte node);
    void caseTAmp(TAmp node);
    void caseTOperators(TOperators node);
    void caseTBrackets(TBrackets node);
    void caseTSymbols(TSymbols node);
    void caseTNumber(TNumber node);
    void caseTString(TString node);
    void caseTBoolean(TBoolean node);
    void caseTIdentifier(TIdentifier node);
    void caseTMisc(TMisc node);
    void caseEOF(EOF node);
}
